### ISSUE TITLE
好像已经失效了

### ISSUE THREAD

**Issue by EverCurse** [tonnie17/one-week#2]
405 非法请求了

**Comment by tonnie17** [comment]
是哪段代码报的错误呢？

**Comment by ghost** [comment]
@tonnie17 
请输入起始站点（输入回车为成都）：
请输入目的站点：常州
请输入出发日期（输入回车为2017-02-10）：2017-02-16
是否成人票，是请按回车，不是请输入n：
正在查询...

https://kyfw.12306.cn/otn/leftTicket/queryZ?leftTicketDTO.train_date=2017-02-16&leftTicketDTO.from_station=CDW&leftTicketDTO.to_station=CZH&purpose_codes=ADULT
Traceback (most recent call last):
  File "E:/Devops/work_scripts/12306.py", line 215, in <module>
    guide()
  File "E:/Devops/work_scripts/12306.py", line 196, in guide
    search(from_city, to_city, train_time, ticket_type)
  File "E:/Devops/work_scripts/12306.py", line 107, in search
    ret = json.loads(urllib2.urlopen(url, context=SSL_CTX, timeout=10).read())
  File "E:\Devops\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "E:\Devops\lib\urllib2.py", line 435, in open
    response = meth(req, response)
  File "E:\Devops\lib\urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "E:\Devops\lib\urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "E:\Devops\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "E:\Devops\lib\urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 405: Method Not Allowed

**Comment by tonnie17** [comment]
看起来是12306又把余票接口换了，我看了http://mobile.12306.cn/weixin/leftTicket/query 这个接口还能使用，需要根据返回内容修改一下
