### ISSUE TITLE
第一个文件分类的Demo的 “back”功能好想无法还原

### ISSUE THREAD

**Issue by pingL** [tonnie17/one-week#3]
➜  01-file-classifier git:(master) ✗ python classify.py -t back /Users/zhaohengyi/Desktop/Shuffle 
Traceback (most recent call last):
  File "classify.py", line 180, in <module>
    _main()
  File "classify.py", line 174, in _main
    go_back(target_dir)
  File "classify.py", line 111, in go_back
    target_dir = target_dir.decode('utf-8')
AttributeError: 'str' object has no attribute 'decode'

**Comment by pingL** [comment]
这个问题解决了，
`target_dir = target_dir.decode('utf-8')`
原文标示解码对象已经解码，，就是str，target_dir不需要在decode，所以改成如下便可
`target_dir = target_dir`
